spring:
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.base-oauth-url}
          jwk-set-uri: ${keycloak.base-oauth-url}/protocol/openid-connect/certs

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs/api-docs
    
# V2 message construction
v2:
  msh:
    sendingApplication: HNWeb
    sendingFacility: HN-WEB
    receivingFacility: BC00001013
    processingID: D

# Fixed Width message construction
fixedWidth:
  header: 
    organization: "00000010"