spring:
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.base-oauth-url}
          jwk-set-uri: ${keycloak.base-oauth-url}/protocol/openid-connect/certs
          audience: MSPDIRECT-SERVICE
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: mspdirect
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
      javax.persistence.create-database-schemas: true

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs/api-docs
    
# V2 message construction
v2:
  msh:
    sendingApplication: HNWeb
    sendingFacility: HN-WEB
    receivingFacility: BC00001013
    processingID: D

# Mapping of roles (SPGs) to specific permissions
security:
  rolePermissions:
    DUMMY:
      - Dummy
    E45:
      - MSPCoverageCheck
    ELIGIBILITY:
      - MSPCoverageCheck
      - CheckEligibility
      - PHNInquiry
    TRAININGHEALTHAUTH:
      - MSPCoverageCheck
      - CheckEligibility
      - PHNInquiry