name: frontend-BuildImageAndPush
# Build the image and deploy in OpenShift environment
env:
  # Registries such as GHCR, Quay.io, and Docker Hub are supported.
  IMAGE_REGISTRY: image-registry.apps.silver.devops.gov.bc.ca/c5839f-tools
  IMAGE_REGISTRY_USER: ${{ secrets.C5839F_OPENSHIFT_GITHUB_ACTIONS_SA_USER }}
  IMAGE_REGISTRY_PASSWORD: ${{ secrets.C5839F_OPENSHIFT_GITHUB_ACTIONS_SA_TOKEN }}
  IMAGE_NAME: hnweb-frontend
  IMAGE_TAGS: 

on:
  push:
    branches:
    - 4969-setup-hnweb

jobs:
  
  buildAndPush:

    runs-on: ubuntu-latest
    
    steps:

    # Checkout code
    - uses: actions/checkout@v2
    - name: checkout
      id: checkout
      working-directory: ./frontend
      with:
        ref: 4969-setup-hnweb