name: BuildAndPush

on:
  push:
    branches:
    - 4241-hnweb-infrastructure
  pull_request:
    branches:
    - 4241-hnweb-infrastructure

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      working-directory: ./frontend
      run: docker build . --file Dockerfile --tag image-registry.apps.silver.devops.gov.bc.ca/c5839f-tools/hnweb-frontend:$(date +%s)

  
  
