name: BuildAndPush

on:
  push:
    branches:
    - 4241-hnweb-infrastructure
  pull_request:
    branches:
    - 4241-hnweb-infrastructure

jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./frontend/Dockerfile --tag image-registry.apps.silver.devops.gov.bc.ca/c5839f-tools/hnweb-frontend:$(date +%s)

    - name: OpenShift login
    - uses: redhat-actions/oc-login@v1.1
      with:
          # Openshift Server URL.
          openshift_server_url: ${{secrets.C5839F_OPENSHIFT_SERVER}}
          # Openshift Bearer Token. Store in a secret.
          openshift_token: ${{secrets.C5839F_OPENSHIFT_GITHUB_ACTIONS_SA_TOKEN}}
          # Set current context's namespace to this, after logging in.
          namespace: c5839f-tools


    - name: Push To Registry
    - uses: redhat-actions/push-to-registry@v2.4
      with:
        image: image-registry.apps.silver.devops.gov.bc.ca/c5839f-tools/hnweb-frontend:$(date +%s) 
  
  
