name: sample-workflow

  

on:
  # Run the workflow manually, instead of on a push.
  # The user specifies the optional tag and branch
  # --------------------------------------------------------------------------
  workflow_dispatch:
    inputs:
      branch:
        description: "Enter branch name (defaults to main):"
        required: true
        default: main

jobs:
  createRtransRelease:
    runs-on: ubuntu-latest


    steps:
      # Check out the code
      - name: Print out 
        id: print
        run: |
          echo "Openshift server is ${{secrets.C5839F_OPENSHIFT_SERVER}}" | sed 's/./& /g'
          echo "Openshift service account is ${{ secrets.C5839F_OPENSHIFT_GITHUB_ACTIONS_SA_USER }}" | sed 's/./& /g'
          echo "Gitops repo is ${{secrets.GITOPS_C5839F_REPO}}" | sed 's/./& /g'
